export const themeColor = 'pink.400'
export const themeColorULight = 'pink.50'
export const themeColorSLight = 'pink.100'
export const themeColorLight = 'pink.300'
export const themeColorDark = 'pink.500'
export const themeColorScheme = 'pink'

export const hiveApi = 'https://techcoderx.com'
export const beApi = 'https://vsc.techcoderx.com/be-api/v1'
export const gqlApi = 'https://vsc.techcoderx.com/api/v1/graphql'
export const cvApi = 'https://vsc.techcoderx.com/cv-api/v1'
export const l1Explorer = 'https://hivehub.dev'
export const l1ExplorerName = 'HiveHub'

export const multisigAccount = 'vsc.gateway'
export const NETWORK_ID = 'vsc-mainnet'
export const NETWORK_ID_ANNOUNCE = 'go-mainnet'
