export const themeColor = 'pink.400'
export const themeColorULight = 'pink.50'
export const themeColorSLight = 'pink.100'
export const themeColorLight = 'pink.300'
export const themeColorDark = 'pink.500'
export const themeColorScheme = 'pink'

export const hiveApi = 'https://testnet.techcoderx.com'
export const beApi = 'https://magi-test.techcoderx.com/be-api/v1'
export const gqlApi = 'https://magi-test.techcoderx.com/api/v1/graphql'
export const cvApi = 'https://vsc.techcoderx.com/cv-api/v1'
export const l1Explorer = hiveApi + '/explorer'
export const l1ExplorerName: string = 'HAF BE'

export const multisigAccount = 'vsc.gateway'
export const NETWORK_ID = 'vsc-testnet'
